apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "albert-docs.fullname" . }}
  labels:
{{ include "albert-docs.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "albert-docs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "albert-docs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/release: "{{ .Values.labels.release }}"
        app.kubernetes.io/product: "{{ .Values.labels.product }}"
        app.kubernetes.io/tier: "{{ .Values.labels.tier }}"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: {{ .Values.nodeAffinity.first.weight }}
            preference:
              matchExpressions:
              - key: product
                operator: In
                values:
                - "{{ .Values.nodeAffinity.first.label }}"
          - weight: {{ .Values.nodeAffinity.second.weight }}
            preference:
              matchExpressions:
              - key: product
                operator: In
                values:
                - "{{ .Values.nodeAffinity.second.label }}"
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          #readinessProbe:
          #  httpGet:
          #    path: {{ .Values.application.health.readiness.uri }}
          #    port: {{ .Values.service.targetPort }}
          #  initialDelaySeconds: {{ .Values.application.health.readiness.initialDelaySeconds }}
          #  timeoutSeconds: {{ .Values.application.health.readiness.timeoutSeconds }}
          #  periodSeconds: {{ .Values.application.health.readiness.periodSeconds }}
          #  failureThreshold: {{ .Values.application.health.readiness.failureThreshold }}
          #livenessProbe:
          #  httpGet:
          #    path: {{ .Values.application.health.liveness.uri }}
          #    port: {{ .Values.service.targetPort }}
          #  initialDelaySeconds: {{ .Values.application.health.liveness.initialDelaySeconds }}
          #  timeoutSeconds: {{ .Values.application.health.liveness.timeoutSeconds }}
          #  periodSeconds: {{ .Values.application.health.liveness.periodSeconds }}
          #  failureThreshold: {{ .Values.application.health.liveness.failureThreshold }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            #requests:
            #  cpu: {{ .Values.resources.requests.cpu }}
            #  memory: {{ .Values.resources.requests.memory }}
          envFrom:
            - configMapRef:
                name: albert-docs-configmap
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
