---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.kubernetesIoIngressClass }}
    traefik.frontend.rule.type: {{ .Values.ingress.traefikFrontendRuleType }}
  name: {{ .Values.ingress.namespace }}-{{ .Chart.Name }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          #serviceName: {{ .Values.ingress.serviceName }}
          serviceName: {{ include "albert-docs.fullname" . }}
          servicePort: {{ .Values.service.port }}
        path: {{ .Values.ingress.path }}
