export default class Seg {
    PAR_ACESSO_TOTAL = "PAR_ACESSO_TOTAL";
    PAR_GRUPO = "PAR_GRUPO";
    PAR_TAB_PARAMETRO_GERAL = "PAR_TAB_PARAMETRO_GERAL";
    PAR_TAB_CONTROLE_CONTA_PI = "PAR_TAB_CONTROLE_CONTA_PI";
    PAR_TAB_CONEXOES_EXTERNAS = "PAR_TAB_CONEXOES_EXTERNAS";
    PAR_TAB_TRANSACOES_AGENDADAS = "PAR_TAB_TRANSACOES_AGENDADAS";
    PAR_BTN_SALVAR = "PAR_BTN_SALVAR";
    PAR_DADOS_ACESSO_STA = "PAR_DADOS_ACESSO_STA";
    PAR_TAB_CERTIFICADO_DIGITAL = "PAR_TAB_CERTIFICADO_DIGITAL";
    PAR_URL_ORQUESTRADOR = "PAR_URL_ORQUESTRADOR";
    PAR_TAB_MONITORAMENTO_FRAUDE = "PAR_TAB_MONITORAMENTO_FRAUDE";
  }
