export default class Seg {
  DAS_MENU = "DAS_MENU";
  DAS_ACESSO_TOTAL = "DAS_ACESSO_TOTAL";
  DAS_3PONTOS_OPCOES = "DAS_3PONTOS_OPCOES";
  DAS_3PONTOS = "DAS_3PONTOS";
  DAS_3PONTOS_DEPOSITO = "DAS_3PONTOS_DEPOSITO";
  DAS_3PONTOS_SAQUE = "DAS_3PONTOS_SAQUE";
  // DAS_WIDGET_3PONTOS_FECHAR = "DAS_WIDGET_3PONTOS_FECHAR";
  // DAS_WIDGET_3PONTOS_CONFIG = "DAS_WIDGET_3PONTOS_CONFIG";
  // DAS_ABA_3PONTOS_ADICIONAR = "DAS_ABA_3PONTOS_ADICIONAR";
  // DAS_ABA_3PONTOS_EXCLUIR = "DAS_ABA_3PONTOS_EXCLUIR";
  // DAS_ADD_ABA = "DAS_ADD_ABA";
}
