export class Seg {
  TMD_SECAO_PESQUISA: string = "TMD_SECAO_PESQUISA";
  TMD_TAB_LIBERADA = "TMD_TAB_LIBERADA";
  TMD_BTN_EXECUTAR_FILTROS = "TMD_BTN_EXECUTAR_FILTROS";
  TMD_BTN_VERIFICAR_MENSAGEM = "TMD_BTN_VERIFICAR_MENSAGEM";
  TMD_LIS_VISUALIZAR = "TMD_LIS_VISUALIZAR";
  TMD_MENU = "TMD_MENU";
  TMD_ACESSO_TOTAL = "TMD_ACESSO_TOTAL";
}
