export class Seg {
  REP_MENU = 'REP_MENU';
  REP_ACESSO_TOTAL = 'REP_ACESSO_TOTAL';
  REP_BTN_ENVIO = 'REP_BTN_ENVIO';
  REP_BTN_ENVIO_REPOSITORIO_SAIDA = 'REP_BTN_ENVIO_REPOSITORIO_SAIDA';
  REP_BTN_FORMATACAO = 'REP_BTN_FORMATACAO';
  REP_BTN_RECEBIMENTO = 'REP_BTN_RECEBIMENTO';
  REP_BTN_REPOSITORIO_ENTRADA = 'REP_BTN_REPOSITORIO_ENTRADA';
  REP_BTN_REPOSITORIO_SAIDA = 'REP_BTN_REPOSITORIO_SAIDA';
}
