# Default values for bancos-pix-front.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sinqia.azurecr.io/core-bancario/pix/bancos-pix-front
  tag: dev
  pullPolicy: Always

imagePullSecrets: []
imagePullSecret: admin-k8s
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# ----------------------------------------
# Limite de CPU e RAM
# ----------------------------------------
#resources:
#  #Mínimo
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  #Máximo
#  limits:
#    cpu: 700m
#    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}

application:
  APP_BASE_HREF: /bancos/pix/
  APP_BASE_URL: https://dev.sinqia.io/bancos/pix

  BACK_UIMANAGER: https://dev.sinqia.io/core-ui-manager-server/api/v2/
  BACK_PIX_CORE: https://dev.sinqia.io/api-bancos-pix-core/v1
  BACK_SEG_CORE: https://dev.sinqia.io/api-bancos-seg-core
  BACK_PIX_WS: https://devl5.sinqia.io/api-bancos-pix-ws/api/v1
  BACK_RELATORIOS_CORE: https://dev.sinqia.io/bancos-spi-relatorios/api/v1
  BACK_GCOB_CORE: https://dev.sinqia.io/api-bancos-gcob-core/api

  AUTH_ISSUER_URL: https://dev.sinqia.io/auth/realms/sinqia
  AUTH_CLIENT_ID: sq-bancos-pix-front
  AUTH_SCOPE: openid profile email
  AUTH_LOG_WARNING_ACTIVE: false
  AUTH_LOG_DEBUG_ACTIVE: false

ingress:
  namespace: dev
  kubernetesIoIngressClass: traefik
  traefikFrontendRuleType: PathPrefixStrip
  host: dev.sinqia.io
  path: /bancos/pix

labels:
  release: dev
  product: core-bancario
  tier: front

nodeAffinity:
  first:
    weight: 99
    label: dhp-core-bancario
  second:
    weight: 1
    label: dhp-core-bancario
