export default class Seg {
  ONB_MENU = 'ONB_MENU';
  ONB_ACESSO_TOTAL = 'ONB_ACESSO_TOTAL';
  ONB_ADICIONAR_USUARIO = 'ONB_ADICIONAR_USUARIO';
  ONB_EDITAR_USUARIO = 'ONB_EDITAR_USUARIO';
  ONB_GERAR_CREDENCIAIS = 'ONB_GERAR_CREDENCIAIS';
  ONB_REENVIAR_CREDENCIAIS = 'ONB_REENVIAR_CREDENCIAIS';
  ONB_GERAR_CERTIFICADO = 'ONB_GERAR_CERTIFICADO';
  ONB_CONFIGURAR_CERTIFICADO = 'ONB_CONFIGURAR_CERTIFICADO';
  ONB_REENVIAR_CERTIFICADO = 'ONB_REENVIAR_CERTIFICADO';
  ONB_GERAR_NOVO_SECRET = 'ONB_GERAR_NOVO_SECRET';
  ONB_CONFIGURAR_ESCOPO = 'ONB_CONFIGURAR_ESCOPO';
}