export default class Seg {
  //composição grupo usuário
  CGU_MENU = 'CGU_MENU';
  CGU_ACESSO_TOTAL = 'CGU_ACESSO_TOTAL';

  //nivel hierarquico
  NVL_MENU = 'NVL_MENU';
  NVL_ACESSO_TOTAL = 'NVL_ACESSO_TOTAL';
  NVL_BTN_NOVO = 'NVL_BTN_NOVO'
  NVL_BTN_EDITAR = 'NVL_BTN_EDITAR'
  NVL_BTN_DELETAR = 'NVL_BTN_DELETAR'

  //grp-usuario
  GRP_MENU = 'GRP_MENU';
  GRP_ACESSO_TOTAL = 'GRP_ACESSO_TOTAL';
  GRP_BTN_NOVO = 'GRP_BTN_NOVO'
  GRP_BTN_ADICIONAR = 'GRP_BTN_ADICIONAR'
  GRP_BTN_VISUALIZAR = 'GRP_BTN_VISUALIZAR'
  GRP_BTN_VINCULAR = 'GRP_BTN_VINCULAR'
  GRP_BTN_EDITAR = 'GRP_BTN_EDITAR'
  GRP_BTN_DELETAR = 'GRP_BTN_DELETAR'

  //usuarios
  USU_MENU = 'USU_MENU';
  USU_ACESSO_TOTAL = 'USU_ACESSO_TOTAL';
  USU_BTN_VISUALIZAR = 'USU_BTN_VISUALIZAR'
  USU_BTN_VINCULAR = 'USU_BTN_VINCULAR'

  //Associação Alçada x Grupo Usuário
  ASS_MENU = 'ASS_MENU';
  ASS_ACESSO_TOTAL = 'ASS_ACESSO_TOTAL';
  ASS_BTN_ADICIONAR = 'ASS_BTN_ADICIONAR'
  ASS_BTN_EXCLUIR = 'ASS_BTN_EXCLUIR'
  ASS_BTN_EDITAR = 'ASS_BTN_EDITAR'

  //Autorizacao x Liberacao
  AUT_MENU = 'AUT_MENU';
  AUT_ACESSO_TOTAL = 'AUT_ACESSO_TOTAL';
  AUT_BTN_PESQUISAR = 'AUT_BTN_PESQUISAR'
  AUT_BTN_ADICIONAR = 'AUT_BTN_ADICIONAR'
  AUT_BTN_EXCLUIR = 'AUT_BTN_EXCLUIR'
  AUT_BTN_EDITAR = 'AUT_BTN_EDITAR'

  //participante indireto
  PTI_MENU = 'PTI_MENU';
  PTI_ACESSO_TOTAL = 'PTI_ACESSO_TOTAL';
  PTI_BTN_NOVO = 'PTI_BTN_NOVO'
  PTI_BTN_EDITAR = 'PTI_BTN_EDITAR'
  PTI_BTN_DELETAR = 'PTI_BTN_DELETAR'
  
  
}
