export default class Seg{
  COB_MENU = "COB_MENU";
  COB_BTN_PESQUISAR = "COB_BTN_PESQUISAR";
  COB_BTN_REPROCESSAR = "COB_BTN_REPROCESSAR";
  COB_BTN_DETCOB = "COB_BTN_DETCOB";
  COB_BTN_COPCOLA = "COB_BTN_COPCOLA";
  COB_BTN_DETCOMPLETO = "COB_BTN_DETCOMPLETO";
}
