export class PermissoesSeg {
  SEG_ADD_USUARIO = 'SEG_ADD_USUARIO';
  SEG_EDI_USUARIO = 'SEG_EDI_USUARIO';
  SEG_PER_USUARIO = 'SEG_PER_USUARIO';
  SEG_TAB_USUARIO = 'SEG_TAB_USUARIO';
  SEG_ADD_GRUPO = 'SEG_ADD_GRUPO';
  SEG_EDI_GRUPO = 'SEG_EDI_GRUPO';
  SEG_PER_GRUPO = 'SEG_PER_GRUPO';
  SEG_TAB_GRUPO = 'SEG_TAB_GRUPO';
  SEG_ACESSO_TOTAL = 'SEG_ACESSO_TOTAL';
  SEG_MENU = 'SEG_MENU';
  SEG_PAS_USUARIO = 'SEG_PAS_USUARIO';
  SEG_ADD_DICIONARIO = 'SEG_ADD_DICIONARIO';
  SEG_EDI_DICIONARIO = 'SEG_EDI_DICIONARIO';
  SEG_PER_DICIONARIO = 'SEG_PER_DICIONARIO';
  SEG_TAB_DICIONARIO = 'SEG_TAB_DICIONARIO';
  SEG_BTN_DEL_DICIONARIO = 'SEG_BTN_DEL_DICIONARIO';
}
