export default class Seg{
  PRC_MENU = "PRC_MENU";
  PRC_ACESSO_TOTAL = "PRC_ACESSO_TOTAL";
  PRC_BTN_EXPORTAR = "PRC_BTN_EXPORTAR";
  PRC_BTN_EXE_FILTRO = "PRC_BTN_EXE_FILTRO";
  PRC_BTN_REENVIAR = "PRC_BTN_REENVIAR";

}
