# Default values for bancos-pix-front.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: us.gcr.io/dhp-bancos/bancos-pix-front
  tag: dev
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

# ----------------------------------------
# Limite de CPU e RAM
# ----------------------------------------
#resources:
#  #Mínimo
#  requests:
#    cpu: 100m
#    memory: 128Mi
#  #Máximo
#  limits:
#    cpu: 700m
#    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}

application:
  APP_BASE_HREF: /bancos/pix/
  APP_BASE_URL: https://devk8.sinqia.com.br/bancos/pix

  BACK_UIMANAGER: https://devk8.sinqia.com.br/core-ui-manager-server/api/v1
  BACK_PIX_CORE: https://devk8.sinqia.com.br/api-bancos-pix-core/v1
  BACK_SEG_CORE: https://devk8.sinqia.com.br/api-bancos-seg-core/api
  BACK_PIX_WS: https://dev.sinqia.com.br/api-bancos-pix-ws/api/v1
  BACK_RELATORIOS_CORE: https://dev.sinqia.com.br/bancos-spi-relatorios/api/v1
  BACK_GCOB_CORE: https://hmg.sinqia.com.br/api-bancos-gcob-core/apis
  BACK_LOG_LEG: https://devk8.sinqia.com.br/aks/bancos-pix-api-log-legado

  AUTH_ISSUER_URL: https://devk8.sinqia.com.br/auth/realms/sinqia
  AUTH_CLIENT_ID: sq-bancos-pix-front
  AUTH_SCOPE: openid profile email
  AUTH_LOG_WARNING_ACTIVE: false
  AUTH_LOG_DEBUG_ACTIVE: false

  # ----------------------------------------
  # Health
  # ----------------------------------------
  health:
    startupProbe:
      uri: /
      initialDelaySeconds: 10
      timeoutSeconds: 5
      periodSeconds: 10
      failureThreshold: 30
    liveness:
      uri: /
      initialDelaySeconds: 150
      timeoutSeconds: 5
      periodSeconds: 30
      failureThreshold: 4

ingress:
  namespace: dev
  kubernetesIoIngressClass: traefik
  traefikFrontendRuleType: PathPrefixStrip
  host: devk8.sinqia.com.br
  path: /bancos/pix

labels:
  release: dev
  product: bancos
  tier: front
