export class Seg {
  BOL_SECAO_PESQUISA: string = "BOL_SECAO_PESQUISA";
  BOL_TAB_MODELO = "BOL_TAB_MODELO";
  BOL_TAB_PRE_BOLETO = "BOL_TAB_PRE_BOLETO";
  BOL_TAB_BLOQUEADO = "BOL_TAB_BLOQUEADO";
  BOL_TAB_LIBERADA = "BOL_TAB_LIBERADA";
  BOL_BTN_PLAY = "BOL_BTN_PLAY";
  BOL_BTN_REFRESH = "BOL_BTN_REFRESH";
  BOL_BTN_PRINT = "BOL_BTN_PRINT";
  BOL_BTN_EXPORTAR = "BOL_BTN_EXPORTAR";
  BOL_BTN_EXECUTAR_FILTROS = "BOL_BTN_EXECUTAR_FILTROS";
  BOL_BTN_NOVO = "BOL_BTN_NOVO";
  BOL_BTN_CANCELAR = "BOL_BTN_CANCELAR";
  BOL_BTN_ALTERAR_PRIORIDADE = "BOL_BTN_ALTERAR_PRIORIDADE";
  BOL_BTN_VERIFICAR_MENSAGEM = "BOL_BTN_VERIFICAR_MENSAGEM";
  BOL_BTN_LIBERAR = "BOL_BTN_LIBERAR";
  BOL_BTN_EXCLUIR = "BOL_BTN_EXCLUIR";
  BOL_BTN_OPCOES = "BOL_BTN_OPCOES";
  BOL_LIS_CLONAR = "BOL_LIS_CLONAR";
  BOL_LIS_EDITAR = "BOL_LIS_EDITAR";
  BOL_LIS_CANCELAR = "BOL_LIS_CANCELAR";
  BOL_LIS_EXCLUIR = "BOL_LIS_EXCLUIR";
  BOL_LIS_VISUALIZAR = "BOL_LIS_VISUALIZAR";
  BOL_MENU = "BOL_MENU";
  BOL_ACESSO_TOTAL = "BOL_ACESSO_TOTAL";
}
